### ISSUE TITLE
Get Heroku deploy working

### ISSUE THREAD

**Issue by chartgerink** [libscie/liberator#11]
Having some trouble with getting the Heroku deploy working, and as a newb I am trying to debug but unable to. See also the most recent [`Procfile`](https://github.com/libscie/liberator/blob/master/Procfile) and [`requirements.txt`](https://github.com/libscie/liberator/blob/master/requirements.txt) for relevant info to solve this error (hopefully).

```
2017-05-31T21:19:13.000000+00:00 app[api]: Build started by user chris@libscie.org
2017-05-31T21:19:36.037729+00:00 app[api]: Release v10 created by user chris@libscie.org
2017-05-31T21:19:36.037729+00:00 app[api]: Deploy 19d74926 by user chris@libscie.org
2017-05-31T21:19:13.000000+00:00 app[api]: Build succeeded
2017-05-31T21:19:37.067617+00:00 heroku[web.1]: State changed from crashed to starting
2017-05-31T21:19:43.870587+00:00 heroku[web.1]: Starting process with command `gunicorn gettingstarted.wsgi --log-file -`
2017-05-31T21:19:48.082048+00:00 heroku[web.1]: Process exited with status 3
2017-05-31T21:19:47.906609+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [4] [INFO] Shutting down: Master
2017-05-31T21:19:47.906681+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-05-31T21:19:47.653255+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [4] [INFO] Starting gunicorn 19.6.0
2017-05-31T21:19:47.654315+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [4] [INFO] Listening at: http://0.0.0.0:48232 (4)
2017-05-31T21:19:47.654467+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [4] [INFO] Using worker: sync
2017-05-31T21:19:47.666210+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [8] [INFO] Booting worker with pid: 8
2017-05-31T21:19:47.684036+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [8] [ERROR] Exception in worker process
2017-05-31T21:19:47.684039+00:00 app[web.1]: Traceback (most recent call last):
2017-05-31T21:19:47.684040+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
2017-05-31T21:19:47.684041+00:00 app[web.1]:     worker.init_process()
2017-05-31T21:19:47.684042+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-05-31T21:19:47.684042+00:00 app[web.1]:     self.load_wsgi()
2017-05-31T21:19:47.684043+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
2017-05-31T21:19:47.684043+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-05-31T21:19:47.684044+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-05-31T21:19:47.684045+00:00 app[web.1]:     self.callable = self.load()
2017-05-31T21:19:47.684045+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-05-31T21:19:47.684046+00:00 app[web.1]:     return self.load_wsgiapp()
2017-05-31T21:19:47.684046+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-05-31T21:19:47.684047+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-05-31T21:19:47.684048+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2017-05-31T21:19:47.684048+00:00 app[web.1]:     __import__(module)
2017-05-31T21:19:47.686111+00:00 app[web.1]: ModuleNotFoundError: No module named 'gettingstarted'
2017-05-31T21:19:47.686688+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [8] [INFO] Worker exiting (pid: 8)
2017-05-31T21:19:47.703410+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [9] [INFO] Booting worker with pid: 9
2017-05-31T21:19:47.722998+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [9] [ERROR] Exception in worker process
2017-05-31T21:19:47.723001+00:00 app[web.1]: Traceback (most recent call last):
2017-05-31T21:19:47.723001+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
2017-05-31T21:19:47.723002+00:00 app[web.1]:     worker.init_process()
2017-05-31T21:19:47.723003+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-05-31T21:19:47.723003+00:00 app[web.1]:     self.load_wsgi()
2017-05-31T21:19:47.723004+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
2017-05-31T21:19:47.723004+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-05-31T21:19:47.723005+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-05-31T21:19:47.723006+00:00 app[web.1]:     self.callable = self.load()
2017-05-31T21:19:47.723006+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-05-31T21:19:47.723007+00:00 app[web.1]:     return self.load_wsgiapp()
2017-05-31T21:19:47.723007+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-05-31T21:19:47.723008+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-05-31T21:19:47.723008+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2017-05-31T21:19:47.723064+00:00 app[web.1]: ModuleNotFoundError: No module named 'gettingstarted'
2017-05-31T21:19:47.723009+00:00 app[web.1]:     __import__(module)
2017-05-31T21:19:47.723328+00:00 app[web.1]: [2017-05-31 21:19:47 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-05-31T21:19:48.097995+00:00 heroku[web.1]: State changed from starting to crashed
2017-05-31T21:20:09.456173+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=libscie.herokuapp.com request_id=d2f0b7a1-a849-487a-af28-61f3f6786e2c fwd="80.115.74.212" dyno= connect= service= status=503 bytes= protocol=https

```

**Comment by chartgerink** [comment]
Solved this for now. Apparently I forgot to adjust `gettingstarted.wsgi` to `liberator.wsgi` and to adjust part of `settings.py` content to `ALLOWED_HOSTS=['*']`.

If problems re-occur, this issue will re-open, but for now we're good.
